#!/bin/sh

set -e

if [ "x$1" = xremove ]; then
	update-alternatives \
		--remove default.plymouth /usr/share/plymouth/themes/piscesys/piscesys.plymouth

        update-alternatives \
		--remove text.plymouth /usr/share/plymouth/themes/piscesys-text/piscesys-text.plymouth
fi

#DEBHELPER#
